services:
    db:
        image: 'postgres:17'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER']
            start_period: 10s
            interval: 5s
            timeout: 10s
            retries: 5
        restart: always
        env_file: docker.env
        environment:
            POSTGRES_USER: '${DATABASE_USER?:DATABASE_USER not set}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD?:DATABASE_PASSWORD not set}'
            POSTGRES_DB: '${DATABASE_NAME}'
        volumes:
            - ./db:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    memory: 1gb
    app:
        build:
            context: .
            args:
                SECRET_KEY: '${SECRET_KEY?:SECRET_KEY not set}'
        image: ku-polls
        command:
            - /bin/sh
            - -c
            - |
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
        env_file: docker.env
        environment:
            SECRET_KEY: '${SECRET_KEY?:SECRET_KEY not set}'
            DATABASE_USERNAME: '${DATABASE_USER?:DATABASE_USER not set}'
            DATABASE_PASSWORD: '${DATABASE_PASSWORD?:DATABASE_PASSWORD not set}'
            DATABASE_NAME: '${DATABASE_NAME}'
            DATABASE_HOST: db
            DATABASE_PORT: 5432
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '8000:8000'
        deploy:
            resources:
                limits:
                    memory: 256mb
